# Generated by Django 4.1 on 2022-11-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_voters_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='block_content',
            new_name='block',
        ),
    ]
