# Generated by Django 4.1 on 2022-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_rename_block_content_voters_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='block',
            field=models.TextField(max_length=64, verbose_name='Block content'),
        ),
    ]
